version: '3'

services:
  pluto:
    build: .
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket:ro
      - .:/app
    tty: true
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    command: bash
